"""Initial complete schema

Revision ID: 0b8570e4df57
Revises: 
Create Date: 2026-09-04 00:03:03.446745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b8570e4df57'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_date', sa.DateTime(), nullable=True),
    sa.Column('on_time_deliveries', sa.Integer(), nullable=True),
    sa.Column('delayed_deliveries', sa.Integer(), nullable=True),
    sa.Column('critical_deliveries', sa.Integer(), nullable=True),
    sa.Column('active_vehicles', sa.Integer(), nullable=True),
    sa.Column('idle_vehicles', sa.Integer(), nullable=True),
    sa.Column('total_incidents', sa.Integer(), nullable=True),
    sa.Column('weather_risk_score', sa.Float(), nullable=True),
    sa.Column('ai_factors', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_metrics_id'), ['id'], unique=False)

    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.String(), nullable=True),
    sa.Column('district_name', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('accessibility_score', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'RESTRICTED', 'HIGH_RISK', 'EMERGENCY', name='districtstatus'), nullable=True),
    sa.Column('geometry', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('districts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_districts_district_id'), ['district_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_districts_district_name'), ['district_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_districts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_districts_state'), ['state'], unique=False)

    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('incident_type', sa.Enum('LANDSLIDE', 'FLOOD', 'ROAD_DAMAGE', 'TRAFFIC', 'WEATHER', name='incidenttype'), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geometry', sa.JSON(), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'MODERATE', 'ELEVATED', 'HIGH', 'CRITICAL', name='risklevel'), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('probability', sa.Integer(), nullable=True),
    sa.Column('timeframe', sa.String(), nullable=True),
    sa.Column('recommendation', sa.String(), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_id'), ['id'], unique=False)

    op.create_table('risk_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_name', sa.String(), nullable=True),
    sa.Column('risk_level', sa.Enum('SAFE', 'LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='risklevel'), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('geometry', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_zones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_zones_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_zones_zone_name'), ['zone_name'], unique=False)

    op.create_table('roads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('road_id', sa.String(), nullable=True),
    sa.Column('road_name', sa.String(), nullable=True),
    sa.Column('road_number', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'RESTRICTED', 'HIGH_RISK', 'BLOCKED', name='roadstatus'), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('road_condition', sa.String(), nullable=True),
    sa.Column('geometry', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roads_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roads_road_id'), ['road_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_roads_road_name'), ['road_name'], unique=False)

    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_name', sa.String(), nullable=True),
    sa.Column('origin', sa.String(), nullable=True),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('estimated_time_minutes', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('SAFE', 'OPEN', 'RESTRICTED', 'HIGH_RISK', 'BLOCKED', name='routestatus'), nullable=True),
    sa.Column('geometry', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_routes_route_name'), ['route_name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'GOVERNMENT', 'LOGISTICS_OPERATOR', 'FIELD_OFFICER', 'EMERGENCY_RESPONSE', 'DRIVER', name='roleenum'), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)

    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_number', sa.String(), nullable=True),
    sa.Column('registration_number', sa.String(), nullable=True),
    sa.Column('vehicle_type', sa.String(), nullable=True),
    sa.Column('cargo_type', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('driver_name', sa.String(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('IDLE', 'MOVING', 'DELAYED', 'STOPPED', 'EMERGENCY', 'OFFLINE', name='vehiclestatus'), nullable=True),
    sa.Column('current_latitude', sa.Float(), nullable=True),
    sa.Column('current_longitude', sa.Float(), nullable=True),
    sa.Column('geometry', sa.JSON(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('current_route_id', sa.Integer(), nullable=True),
    sa.Column('current_delivery_id', sa.Integer(), nullable=True),
    sa.Column('last_gps_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_vehicle_number'), ['vehicle_number'], unique=True)

    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_number', sa.String(), nullable=True),
    sa.Column('cargo_type', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('origin', sa.String(), nullable=True),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('origin_lat', sa.Float(), nullable=True),
    sa.Column('origin_lng', sa.Float(), nullable=True),
    sa.Column('destination_lat', sa.Float(), nullable=True),
    sa.Column('destination_lng', sa.Float(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'ASSIGNED', 'IN_TRANSIT', 'DELAYED', 'DELIVERED', 'CANCELLED', 'EMERGENCY', name='deliverystatus'), nullable=True),
    sa.Column('progress_percentage', sa.Float(), nullable=True),
    sa.Column('estimated_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deliveries_delivery_number'), ['delivery_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_deliveries_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deliveries_id'))
        batch_op.drop_index(batch_op.f('ix_deliveries_delivery_number'))

    op.drop_table('deliveries')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_vehicle_number'))
        batch_op.drop_index(batch_op.f('ix_vehicles_id'))

    op.drop_table('vehicles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.drop_index(batch_op.f('ix_users_name'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routes_route_name'))
        batch_op.drop_index(batch_op.f('ix_routes_id'))

    op.drop_table('routes')
    with op.batch_alter_table('roads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roads_road_name'))
        batch_op.drop_index(batch_op.f('ix_roads_road_id'))
        batch_op.drop_index(batch_op.f('ix_roads_id'))

    op.drop_table('roads')
    with op.batch_alter_table('risk_zones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_zones_zone_name'))
        batch_op.drop_index(batch_op.f('ix_risk_zones_id'))

    op.drop_table('risk_zones')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_id'))

    op.drop_table('incidents')
    with op.batch_alter_table('districts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_districts_state'))
        batch_op.drop_index(batch_op.f('ix_districts_id'))
        batch_op.drop_index(batch_op.f('ix_districts_district_name'))
        batch_op.drop_index(batch_op.f('ix_districts_district_id'))

    op.drop_table('districts')
    with op.batch_alter_table('daily_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_metrics_id'))

    op.drop_table('daily_metrics')
    # ### end Alembic commands ###
